### ISSUE TITLE
Libresonic 6.2 Release Plan

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#153]
This will be the Omnibus Release Plan for Libresonic 6.2. This is an information-only Issue; please limit discussions to IRC or other Issues. This will be a development release, meaning that there will be a lot of breakage in the develop branch before it is stable. The main goals for this release are:

1. Reduce the project scope by removing legacy features that are unmaintained, poorly-written, or a bad idea.
    - [X] Remove UPnP. This technology is a bad idea.
    - [X] Remove vestigal licensing code(#77)
    - [X] Remove the Chat feature. Please migrate to the chat platform of your choice; this is not Libresonic's job.
    - [X] Remove remote-access service (yourname.libresonic.org), this service will not be provided. Using your own domain is recommended.
    - [X] ~~Deprecate Casting. A maintainer is welcomed to port this feature to the new media-router implementation, or it will be removed in a future release. (#130)~~ Updated in #195 
    - [ ] ~~Deprecate Sonos and DLNA. These features are untested and a maintainer is welcome to bring them up-to-date, or they will be removed in a future release.~~ Interest has been expressed in keeping these features, so delaying decision until 6.3
2. Bring the codebase up to modern standards and libraries.
    - [X] Update to a newer version of Spring(#80)
    - [X] Replace subsonic-booter with Spring Boot(#142)
3. Improve existing functionality
    - [ ] ~~Automatically locate transcoder binaries(ffmpeg)~~ Delayed until 6.3 due to issues, see #174 
4. Implement oft-requested features as possible.
    - [X] Demo site (#116)
    - [X] External database support(#62)

**Comment by EugeneKay** [comment]
Lots of progress has been made lately, particularly with regards to Spring & friends. I'm planning to make a "6.2.beta1" release this week so it can get put through its paces. I'd like to do a beta release every month(or few weeks, if feasible) as progress allows.

**Comment by muff1nman** [comment]
How do we want to handle the chat API being used in client applications such as Android?

**Comment by 3615pipou** [comment]
>  Remove the Chat feature. Please migrate to the chat platform of your choice; this is not Libresonic's job.

Me be a pre-install XMPP client conversejs would be a good solution to replace it see #194

**Comment by stevenroose** [comment]
I'd like to take a look at Sonos. Problem is that I currently don't have access to the server machine that I want to install the Libresonic on. It's at home and I live abroad.

I might create a setup on my machine just for this purpose though, but the earliest in a week or three.

**Comment by jooola** [comment]
Could we have some feedback @EugeneKay ? To see what's left todo ?
Some issue are already closed and solved,could you mark it ?

**Comment by EugeneKay** [comment]
@jooola I have previously "Marked" some of these items as complete, but Github's javascript does not seem to have made it stick. Per conversation with @muff1nman separately we have set an arbitrary goal date of April 1, 2017 for 6.2 and a Beta1 date of March 5th, 2017. I am leaving myself a TODO of fixing the above checklist and adding/removing items before then.

**Comment by muff1nman** [comment]
@EugeneKay Marked the completed items by editing the comment to change `[ ]` to `[X]`

**Comment by EugeneKay** [comment]
:tableflip:

**Comment by EugeneKay** [comment]
v6.1.beta1 has been tagged & released, use at your own risk. Worth noting that it did not start on the demo site, but I'm not looking into it today.

**Comment by EugeneKay** [comment]
v6.2.beta2 was tagged & released, and there was much rejoicing.

v6.2.beta3 has been tagged & released as well, and merged into the stable branch, Please test vigorously, and submit any 6.2 issues against the stable branch. Final release will be around the end of this month.

**Comment by EugeneKay** [comment]
v6.2.beta4 is out now. v6.2 Final will be released on Sunday(April 30th). Submit any bugfixes by then.

**Comment by EugeneKay** [comment]
v6.2 has been released, only a month behind the original date(April 1st). I call this a success.

**Comment by biconou** [comment]
Isn't it Libresonic's first anniversary ?
