### ISSUE TITLE
Broken pages and forms

### ISSUE THREAD

**Issue by fxthomas** [Libresonic/libresonic#244]
A few pages are broken and need fixing :

- [x] The form in `db.view` fails because of an unsupported method (#245)
- [x] The shuffle radio form in `more.jsp` fails because of a CSRF failure (#246)
- [x] The "Status" page crashes (#247)

**Comment by fxthomas** [comment]
Ran a quick test through Libresonic and added PRs for broken pages and forms. The should be enough for the web UI ; the REST API has been working fine for me for a few weeks.

**Comment by fxthomas** [comment]
This is merged, so closing.
