### ISSUE TITLE
Rebrand to Libresonic

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#40]
Reference history from #36.

There will be a fork of the upstream Subsonic project, which is no longer open-source for 6.0+. The 5.3 codebase(and previous) are licensed under GPLv3, which is already contained here. This issue exists to track the rebrand effort associated with this fork.

In the short term, we must:
- [x] Secure a suitable domain name, eg libresonic.org
- [x] Update the repository documentation(#39).
- [x] Rebase against "new" git history instead of SVN import(#41)
- [x] String-change usage of "Subsonic" in the application(#42)
- [x] Create a new logo. Input and contribution is welcomed(#43)
- [x] Move to Semantic Versioning and modify updater(#44)

Long-term cleanup goals:
- [x] Rename out of the subsonic Java namespace(#52)
- [x] Change remaining user-facing strings
- [x] [Create a website](https://github.com/Libresonic/libresonic.github.io)
- [ ] ~~Contact maintainers of client libraries to provide a FOSS alternative to the now-closed Subsonic~~
- [x] Provide documentation for installation, usage, etc(#64)

Contributions are welcomed in the form of a Pull Request or separate Issue. Additional ideas are welcomed as a comment, but may be ignored.

**Comment by EugeneKay** [comment]
I have purchased libresonic.org. HTTP is redirected to this repo on Github.

**Comment by TroyArnason** [comment]
I think switching to html5 jwplayer would be a good change.

**Comment by votacom** [comment]
OMG, I just thought yesterday about what to do about this devolpment and decided to fork my own version from 6.0-beta1. Thinking of a name, I decided on "LibreSonic". What a coincidence :D
Count on me.

**Comment by Lawrence5** [comment]
Not that I don't appreciate all that you've done here. I do. But how will Libresonic be different from Futuresonic and Madsonic?

**Comment by votacom** [comment]
Madsonic is not open source. Futuresonic seems to be somewhat dead.

**Comment by surfrock66** [comment]
What was the last GPL release...5.3, or 6 b1?

**Comment by votacom** [comment]
6.0-beta1 was the last source code release and it was released under GPL.

**Comment by surfrock66** [comment]
Is it possible for Libresonic to fork from the 6.0b1, instead of 5.3?  I can't find the 6.0b1 code anywhere.

**Comment by votacom** [comment]
6.0-beta1 source:
https://sourceforge.net/projects/subsonic/files/subsonic/6.0.beta1/

**Comment by jayesbe** [comment]
I second forking from 6.0

**Comment by surfrock66** [comment]
Since you've bought a domain, is there somewhere we can contribute a few bucks?

**Comment by hanspeter1** [comment]
Madsonic is open source: https://gitlab.com/madsonic/madsonic-main/tags

**Comment by votacom** [comment]
Oh, I assumed it to be closed source, since they do not provide a source download on their homepage. Are the "premium features" unlocked by a license that is coped with by open-source license-checking code (as it was with subsonic until now)?

**Comment by votacom** [comment]
Well, if Madsonic is indeed open source, it might be a good idea to fork it instead of Subsonic, since the upstream will presumably longer stay FOSS. We might just get rid of the license-checking code in our fork.

**Comment by surfrock66** [comment]
If there's any voting/poll, the interface for subsonic 6.0 is nice, I find it scales and responds better.  I think it's a great place to start.

**Comment by jooola** [comment]
Great idea to fork the project here !
I think starting with subsonic 6.0b1 is the best solution !
Madsonic is not as clean as Subsonic ! Sindre mad a really clean work !
I prefer start on a clean (not too buggy ) base than a mess ( buggy as hell ) ! ( maybe just get some features from madsonic and rewrite it here ? )

Subsonic 6.0b1 has a nice interface yes  i agree !

We may share the Subsonic API with the Ampache project in Gihub ! 

I don't get why Sindre Mehus put his code on github 
[https://github.com/sindremehus/subsonic](url) 
Any ideas ?

Joola

**Comment by votacom** [comment]
Well, I wouldn't assume that github.com/sindremehus/subsonic is the real codebase for Subsonic 6. Nevertheless, it might be a good source for anything that changed since 6.0-beta1.

**Comment by jooola** [comment]
Yeah, its written at bottom its the 5.3 code !
what i don't understand is why he just created the repo, if he want to build closed softwares ?

**Comment by EugeneKay** [comment]
Please do not use this Issue as a conversation thread. I will post an update in a few hours, including some of the feedback from here. Thank you for your patience.

**Comment by EugeneKay** [comment]
I have moved this repository from EugeneKay/subsonic to LIbresonic/libresonic. Several new issues have been created to track sub-tasks.

#39 and 9e53ac1 update the repository documentation.

I have removed chatter commentary from this Issue. I have taken note of the questions and issues mentioned. Several of them will be appearing as separate Issues shortly. You can join #libresonic on Freenode, but be patient as I often ignore IRC for long periods.

**Comment by csobsidian** [comment]
Is there a preferred namespace to move into?

**Comment by EugeneKay** [comment]
Actual work on future goals should wait until after the rebase(#41), since the git history will be completely rewritten. I will have some time this weekend to work on that.

I do not have a preference for the package rename. Currently it is "net.sourceforge.subsonic"; following the Java convention will yield "org.libresonic.player", but I have other priorities first. Feel free to continue this as a separate Issue to discuss the implications and planning.

I have added some Milestones and Labels. Please feel free to contribute to everything marked as discuss or patches-welcome. Art mockups(logo or website) would be spectacular; I do not have the talent for it.

**Comment by csobsidian** [comment]
Move to namespace added as issue #52. I'm happy to start tackling this as soon as issue #41 is taken care of.

**Comment by miicha** [comment]
I'm curious why you didn't fork the 6.0.beta1 which seems to be licensed under GPL according to the readme: http://svn.code.sf.net/p/subsonic/code/tags/release-6.0.beta1/subsonic-main/README.TXT
I really like the HTML5 player in this version which runs fine at least fo rmy needs.

**Comment by EugeneKay** [comment]
There are three major reasons that 5.3 is the starting-point for this Fork effort. In no particular order:

1. It's the last "stable" release that was open-source
2. The features in 6.0-beta1 are buggy and not complete
3. I don't like the new layout

It is very likely that some of the new features from the beta will be cherry-picked, but that will be a case-by-case basis with no timeline set.

**Comment by EugeneKay** [comment]
I have completed #41. You should re-clone/fork the new history.

**Comment by EugeneKay** [comment]
@csobsidian submitted PR #59 which fulfills #42

**Comment by EugeneKay** [comment]
583d45a was merged in #59 which included a temporary logo from @csobsidian. That is "good enough" progress on #43 for this issue, so I am marking it complete. The long-term logo competition is ongoing - please submit your entries and vote!

**Comment by EugeneKay** [comment]
#44 has been completed. Tag+build for 6.0 incoming shortly.

**Comment by EugeneKay** [comment]
I have tagged+release [v6.0.1](https://github.com/Libresonic/libresonic/releases/tag/v6.0.1).

**Comment by jooola** [comment]
I don't understand something : Should be rename EVERY subsonic entries into libresonic ? even in the code ? or not ? if yes we should start right now :p

**Comment by EugeneKay** [comment]
I have tagged+released v6.1.beta2. Please download, test, and report Issues(or submit a PR!). I would like to make a proper 6.1 release this weekend.
